// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIbyOqj7fHAIFx35HKyXTV9Nff6EQqnfc',
    appId: '1:358601933529:web:7b516f84486483936ef4c8',
    messagingSenderId: '358601933529',
    projectId: 'aporia-network',
    authDomain: 'aporia-network.firebaseapp.com',
    databaseURL: 'https://aporia-network-default-rtdb.firebaseio.com',
    storageBucket: 'aporia-network.appspot.com',
    measurementId: 'G-11Q1ZD43GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_vO8pFvLn2fy-50DMnxsuElZigDbMev0',
    appId: '1:358601933529:android:2364b061551b873b6ef4c8',
    messagingSenderId: '358601933529',
    projectId: 'aporia-network',
    databaseURL: 'https://aporia-network-default-rtdb.firebaseio.com',
    storageBucket: 'aporia-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxSoJeqdgzLyBBJAYc_halNbWEAuBzjo',
    appId: '1:358601933529:ios:1acd8adbb74887386ef4c8',
    messagingSenderId: '358601933529',
    projectId: 'aporia-network',
    databaseURL: 'https://aporia-network-default-rtdb.firebaseio.com',
    storageBucket: 'aporia-network.appspot.com',
    androidClientId: '358601933529-bsf3ecuhildi5ldasebt0c0clkdigrmu.apps.googleusercontent.com',
    iosClientId: '358601933529-b61441s1fpp2b63t6so2esjl5k4ff0d1.apps.googleusercontent.com',
    iosBundleId: 'com.aporia.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcxSoJeqdgzLyBBJAYc_halNbWEAuBzjo',
    appId: '1:358601933529:ios:1acd8adbb74887386ef4c8',
    messagingSenderId: '358601933529',
    projectId: 'aporia-network',
    databaseURL: 'https://aporia-network-default-rtdb.firebaseio.com',
    storageBucket: 'aporia-network.appspot.com',
    androidClientId: '358601933529-bsf3ecuhildi5ldasebt0c0clkdigrmu.apps.googleusercontent.com',
    iosClientId: '358601933529-b61441s1fpp2b63t6so2esjl5k4ff0d1.apps.googleusercontent.com',
    iosBundleId: 'com.aporia.ios',
  );
}
