// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlghGm4XrM9js7nXyENPW7oAtrxlq0xYw',
    appId: '1:1001095842193:web:7c3413d37d04c61836b230',
    messagingSenderId: '1001095842193',
    projectId: 'cgs-maths-club',
    authDomain: 'cgs-maths-club.firebaseapp.com',
    storageBucket: 'cgs-maths-club.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ApAhNWmHqgHKxaDEs2cvPe7W8IXGoEs',
    appId: '1:1001095842193:android:356bf89f97b5996436b230',
    messagingSenderId: '1001095842193',
    projectId: 'cgs-maths-club',
    storageBucket: 'cgs-maths-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD2RCwFYf1KC5mJZrByzNn0Unz8L6bfgg',
    appId: '1:1001095842193:ios:fea8fa6d60f98e1136b230',
    messagingSenderId: '1001095842193',
    projectId: 'cgs-maths-club',
    storageBucket: 'cgs-maths-club.appspot.com',
    iosClientId: '1001095842193-tjjil8elv8opuf533muk1qi69atstnvj.apps.googleusercontent.com',
    iosBundleId: 'com.garv.mathsClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD2RCwFYf1KC5mJZrByzNn0Unz8L6bfgg',
    appId: '1:1001095842193:ios:fea8fa6d60f98e1136b230',
    messagingSenderId: '1001095842193',
    projectId: 'cgs-maths-club',
    storageBucket: 'cgs-maths-club.appspot.com',
    iosClientId: '1001095842193-tjjil8elv8opuf533muk1qi69atstnvj.apps.googleusercontent.com',
    iosBundleId: 'com.garv.mathsClub',
  );
}
